test:
	/home/bitcom/IPNC_RDK_V3.8.0/Source/ti_tools/linux_devkit/bin/arm-arago-linux-gnueabi-g++  test.cpp -o test -lJson -L/home/bitcom/IPNC_RDK_V3.8.0/Source/ipnc_rdk_kk/ipnc_app/vd/lib/Json/lib

clean:
	rm test

