* 全联网智能车位锁本地网络通信协议 Ver1.0

** 简介：

    全联网智能车位锁采用Zigbee 通信方式，由物联网网关、路由器和车位锁等构成一个树形自愈网络。
车位锁搭载Zigbee 节点模块，网关作为Zigbee 网络的协调器负责网络的建立和维护，通过增加路由器以扩
展Zigbee 网络的空间范围及节点数量。
    车位锁通过Zigbee 组成网络，其底层基于IPv6，外部必须通过网关访问Zigbee 网络内的车位锁，本
文档详细介绍了通信接口及协议。物联网网关具备socket 接口，每个设备（网关、路由、车位锁）都具备
唯一的mac 地址，该地址为128 位编码格式，采用16 字节16 进制数表示（如：00158D0000CAB827），
对于车位锁的访问必须指定其mac 地址，另外使用“001500FFFFFFFFFF”作为网关的专用虚拟地址，用于针
对网关的访问。

** 通信接口：

    物联网网关socket 接口采用基于IPv4 的TCP/IP 协议，网关作为TCP Server 监听8008 端口，可以使用
client 连接该端口，通信数据采用json 格式。

接口实例：

#+BEGIN_SRC
{ "ver": 1,
  "mac": "00158D0000CAB827",
  "code": "GET",
  "type": "NON",
  "payload": "[01:01]"
}
#+END_SRC

接口解析：

- "ver": 表示协议的版本号，目前协议版本1；
- "mac": mac 地址， 车位锁的mac 地址， 每个车位锁都有一个唯一的mac 地址；
         “001500FFFFFFFFFF”是网关专用虚拟地址地址，对网关进行操作时采用该mac 地址；
- "code": 指令类型，暂未使用，填写“GET”；
- "type": 消息类型，CON 代表需要回复确认消息，当车位锁收到指令数据时会首先应答“ACK”，然
  后再执行指令动作，当Zigbee 网络状况较差导致车位锁未能收到指令时，网关会自动进
  行指令重发，如果网络一直没有恢复网关将在重试5 次后结束重发；NON 代表不需要回复
  确认消息，车位锁不返回应答信息，网关也不会进行数据重发；
- "payload": 指令数据，本部分数据是指令数据，车位锁或网关解析并执行这里的指令，详见通信
  协议；

    当TCP client 连接到网关的8008 端口后，通过以上格式向网关发送数据，网关收到数据后，会
解析数据，判断mac 地址并将payload 数据发向mac 地址对应的车位锁，车位锁收到payload 数据后
执行动作，车位锁的回复数据经网关传送给TCP client，返回数据格式如下所示：

#+BEGIN_QUOT
{ "type": "DATA",
  "mac": "00158D0000CAB827",
  "code": "GET",
  "ver": 1,
  "payload": "[40:2010000]"
}
#+END_QUOT

接口解析：
- "type": 回复数据类型，分为DATA 和ACK，DATA 表示该帧为数据帧，需要解析payload 数据。
  ACK 表示应答帧，是针对“CON”型指令的应答消息；
- "mac": 车位锁的mac 地址，“001500FFFFFFFFFF”是网关专用虚拟地址地址；
- "code":指令类型，暂未使用，固定为“GET”；
- "ver": 通信协议版本；
- "payload": 车位锁或网关返回的数据，相见通信协议；

** 通信协议：

通信协议数据遵循如下格式：[cc:d…d]

| 起始位 | 指令域 | 分割位 | 数据域*1 | 结束位 |
|--------+--------+--------+----------+--------|
| [      | cc     | :      | d ... d  | ]      |
| 1byte  | 2byte  | 1byte  | nbyte    | 1byte  |

*1 数据域为动态长度，不同指令的回复数据长度可能不一样。
目前支持的指令列表：

| 指令 | 定义                | 指令执行者 |
|------+---------------------+------------|
| 01   | 升降控制指令        | 车位锁     |
| 04   | 状态查询指令        | 车位锁     |
| 0A   | 蜂鸣器控制指令      | 车位锁     |
| F0   | 刷新Zigbee 网络指令 | 网关       |
| F1   | 读取车位锁列表指令  | 网关       |

1. “01”升降控制指令，数据域长度为2。
  + 升指令：[01:01]
  + 降指令：[01:02]
2. “04”高级查询指令，数据域长度为2，数据为“01”
  回复消息：[4A:DBCXXXX]，数据域长度为7。
A: 错误码：0：OK， 1：mag err
D: 摇臂复位控制源
0- 摇臂自动复位
1- 远程控制复位
2- 蓝牙控制复位
3- 超声检测无车复位
B：报警码：0-报警音，1-没有报警音
C：摇臂位置：
   1- 上锁
   2- 解锁
   3- 异常
   XXXX：剩余电量信息
3. “0A”蜂鸣器控制指令，数据域长度为2，表示蜂鸣器鸣响时间（秒）。例如[0A:01]
   控制蜂鸣器鸣响1 秒。
4. “F0”网关刷新Zigbee 节点，数据域长度为2，数据固定为“01”
   由于网关刷新Zigbee 节点速度较慢，该指令采取异步操作模式，网关收到指
   令后开始执行，并实时返回执行状态，待刷新指令执行完毕后通过读取节点列表
   指令获得节点列表
   ，待刷新指令执行完毕后通过读取节点列表

     回复消息：[F0:01]-开始刷新Zigbee 节点
     回复消息：[F0:02]-刷新完成
     回复消息：[F0:03]-发生错误
5. “F1”读取该网关下当前已连接的车位锁列表，数据域长度为2，数据固定为
   “01”
     回复消息：[F1:(‘count’:’x’,’index’:’x’,’node’:’n1,n2,…nx’)]
    由于一个网关管理的车位锁的数量可能较多，一次传回全部车位锁信息将导
致数据帧体积过于庞大，所以采用分包传送的机制，每个回传的数据帧最多包含
20 台车位锁。回复数据指令域固定为F1；count 描述车位锁的总数量；index 描
述当前数据帧编号，编号从1 开始；node 描述节点mac 地址，节点之间以“,”分
割。
